Update concat strategy; Fix sourcemap support in Ember v2 pipeline
linkedin/css-blocks pull request #492
Opened 2020-08-29 00:14 UTC by timlindvall

2020-08-29 00:44 UTC, chriseppstein commented on packages/@css-blocks/ember/src/index.ts
> +    return withoutCssBlockFiles(tree, true);
I noticed this the other day. Thank you for fixing it!

2020-09-02 19:01 UTC, ramitha approved these changes
Does this mean we won't need the the `import 'css-blocks'` within the app.(s)css file?

2020-09-02 23:09 UTC, timlindvall commented
> Does this mean we won't need the the `import 'css-blocks'` within the app.(s)css file?

Yes, `broccoli-concat` will merge the files together. We'll provide the ability to override concat settings in the event there's multiple files to merge together or apps want to change the order.

2020-09-02 23:58 UTC, chriseppstein requested changes
This is great stuff. I'm glad you got this working, it's super important to the developer experience. I think it needs a few small changes and then it will be ready to merge.

2020-09-02 23:58 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/index.ts
> +    inputFiles: ["assets/css-blocks.css", `assets/${env.modulePrefix}.css`],
This should use the output of `cssBlocksOutputFilename()` instead of hardcoding `assets/css-blocks.css` so that it respects the `output` filename configuration.

2020-09-02 23:58 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/index.ts
> +      }
It's slightly less efficient, but I think we should move the conditional check into the expression, it cleans up some of the duplication and makes this block easier to read.

```suggestion
      let concatOptions: BroccoliConcatOptions = Object.assign(
        {},
        buildDefaultBroccoliConcatOptions(env),
        env.config.broccoliConcat || {},
      );
```

2020-09-02 23:58 UTC, chriseppstein commented on packages/@css-blocks/ember-utils/src/options.ts
> +  broccoliConcat: BroccoliConcatOptions | "SKIP";
I prefer `false` to the string literal `"SKIP"` here. It means that down on line 80 you'll need to check for `undefined` explicitly, but I think it's a more standard API for the user.

Alternatively, you can add an option like `disableBroccoliConcat` that is at the same level as `broccoliConcat` and it would cause the concat to be skipped if set to true, even if concat options were provided.

2020-09-02 23:58 UTC, chriseppstein commented on packages/@css-blocks/ember-utils/src/options.ts
> +   * at "styles/css-blocks.css", but will vary if the "output" property is set
I thought these files were in the `assets` directory instead of the `styles` directory... that's what we're using in the config defaults at least.

```suggestion
   * at "assets/<name-of-file>.css". You can use a plugin such as broccoli-debug
   * to determine the structure of your styles after processing.
   *
   * Your CSS Blocks file will be available by default
   * at "assets/css-blocks.css", but will vary if the "output" property is set
```

2020-09-03 00:06 UTC, timlindvall commented on packages/@css-blocks/ember-app/src/index.ts
> +          env.config.broccoliConcat,
They may want to disable sourcemaps altogether, or they may want to make the sourcemap inline, or some other config I'm not thinking of. I think my goal here was to muck with what the user gives as minimally as possible, but it's true things would break if we omit some things.

I'll update this to be smarter about how we're merging this object together.

2020-09-03 21:15 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/index.ts
> +  const cssBlocksOutputFilename = env.config.output || "css-blocks.css";
I'd prefer that we didn't duplicate the logic for accessing this option with a default. Is there a reason why the function I suggested couldn't be used?

2020-09-03 21:17 UTC, chriseppstein approved these changes
One comment. Approved to merge once that's addressed.

2020-09-03 21:21 UTC, timlindvall commented on packages/@css-blocks/ember-app/src/index.ts
> +  const cssBlocksOutputFilename = env.config.output || "css-blocks.css";
The paths are different. The aforementioned method presumes `app/styles/`, but the path should be `assets/`.

2020-09-03 21:53 UTC, merged