Test support for Ember Apps
linkedin/css-blocks pull request #499
Opened 2020-09-12 02:47 UTC by ramitha

Resolves #480 

Adding test support for ember apps that depend on @css-blocks/ember-app. 

We introduce a test-support method called `setupCSSBlocksTest` that's responsible for setting up the test infrastructure.
- This involves extending the `-css-blocks` service and overriding the class names omitted by the service to include fake classNames for all the elements. 
- This method also exposes the CSSBlocksTestService itself via `this.cssBlocks` that has a single API called `getBlock` that can then be queried for these fake classNames. 

For this API to function, we generate `css-blocks-test-support-data` during build that the testService can talk to.

2020-09-12 07:38 UTC, chriseppstein requested changes
This is a great start @ramitha! I really like the overall structure of the testing solution that you've put together here. I think most, if not all, of the issues I've raised here are going to be fairly straightforward to resolve.

2020-09-12 07:38 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
I don't understand why you're using the factory to get the block again. I think you can just do `block.eachBlockExport()`.

2020-09-12 07:38 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +        if (block.identifier.startsWith(IDENTIFIER_PREFIX)) {
There's a method to check for this in `BroccoliTreeImporter`:

```suggestion
        if (isBroccoliTreeIdentifier(block.identifier)) {
```

2020-09-12 07:38 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let filePath = pathToIdent(filename).split(".compiledblock.")[0].replace(IDENTIFIER_PREFIX, "");
I don't understand why you're working your way from the filename to the identifier with `pathToIdent()` when you can just use `block.identifier`.

2020-09-12 07:38 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +
This is going to grab every block that's in the broccoli tree which is every addon, every engine, and the app too. I think this exposes too much to the tests. I don't think the tests should be able to access any block that isn't one of their app's blocks or exported from one of their app's own blocks. Can we restrict this to just the application's blocks? If not, what is the use case that I'm missing here?

2020-09-12 15:47 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks.ts
> +  static enableTestMode: Boolean = false;
Ah, thank you!

2020-09-12 16:13 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks.ts
> +    return this.getImpliedAndOptimizedStyles(stylesApplied);
Sure. I refactored this bit initially when I was using this method to get the actual classNames.

2020-09-12 16:20 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +        "setupTracking must be called after setupTest|setupRenderingTest|setupApplicationTest",
Yes, I used ember-cli-pemberly-tracking as a reference for how to provide test scaffolding.

2020-09-12 16:26 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +// TODO: get qunit types
Good point. The standard way is to use `ember-qunit`, but people can also use `ember-mocha` and both of these provide the same functionality for setting up different types of ember tests. I'll make a note of it in the comments.

2020-09-12 16:31 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +    return `${this.blockId}${styleName.replace('"', "")}`;
I'm also debating whether we want to provide a more meaningful error message here with the list of available styles if the style supplied is not found

2020-09-12 16:36 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
Good catch. This was before the export bug was filled and when I was trying to see if the original block contained the exported blocks.

2020-09-12 16:43 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
Hmm.. the block in context is the compiled block that doesn't have the exported blocks on it. Could this be another bug?

2020-09-12 16:43 UTC, chriseppstein commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +    return `${this.blockId}${styleName.replace('"', "")}`;
@ramitha That's a great idea!

2020-09-12 16:50 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +
I'm iterating through all the blocks because I not only need the blocks exposed by the app, but also those of an addon. The use case here is, if I have an ember addon that contains a component, the dummy app should be able to access the blocks for the component in its acceptance tests. 

The way I'm filtering down to the app's blocks and the addon's blocks while building the test data is by checking if the `block.identifier` starts with `IDENTIFIER_PREFIX`(line 79). If it's an absolute path, we can assume that it's not a part of this module and we don't add that to the test data.

2020-09-12 16:55 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
Yes, the compiled block should have the exported blocks. If not there, that's definitely a bug.

2020-09-12 17:12 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +
> The use case here is, if I have an ember addon that contains a component, the dummy app should be able to access the blocks for the component in its acceptance tests.

ok. So the specific use case is that the tests want to test the addon's internals without exposing the addon's blocks via the `css-blocks.main` property in `package.json`? That's a good use case. Thanks.

The current implementation appears to expose all addons to the tests, even for applications that are not addons undergoing test.

I think we can handle this specific situation by using block aliases to expose the addon's blocks to the dummy app's templates without exposing the blocks to NPM import. The export doesn't have to be used in the template, it can just exist for testing purposes. If we do that, we can simplify the metadata generation to just blocks that are part of the main application, yes?

2020-09-12 17:17 UTC, chriseppstein commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +// TODO: get qunit types
> both of these provide the same functionality for setting up different types of ember tests.

Does this mean they provide compatible APIs for our needs and that our code will work for both?

2020-09-12 17:20 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
Does the fix to `@css-blocks/core/src/BlockParser/features/export-blocks.ts` not remedy this?

2020-09-14 17:48 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +// TODO: get qunit types
Yes, they do. `ember-mocha` also exposes the same setup functions and sets `this.owner` (from their README) and `mocha` has a `beforeEach` hook,  so our code will work. It looks like we aren't using it at all at LinkedIn though, so I haven't tested it.

2020-09-14 17:56 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +// TODO: get qunit types
Also, any framework can override the runtime service to use the test service instead (if they have to using different hooks)

2020-09-14 18:43 UTC, chriseppstein commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks-test-support.ts
> +// TODO: get qunit types
Ok. As long as the main use cases are covered here, I'm happy. We can tackle other testing frameworks on an as-needed basis.

2020-09-14 19:26 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
No, it doesn't. I better write a test for this.

2020-09-14 20:00 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +
As discussed, this will expose blocks within in-repo addons and in-repo engines to the tests as well. Anything that is not in-repo will not be exposed to the test. Resolving this for now.

2020-09-16 20:06 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let filePath = pathToIdent(filename).split(".compiledblock.")[0].replace(IDENTIFIER_PREFIX, "");
Sorry for the mess. Cleaned it up a bit.

2020-09-16 20:07 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
Turns out the test passes but I was missing a yarn link into @css-blocks/core.

2020-09-16 20:07 UTC, ramitha commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let filePath = pathToIdent(filename).split(".compiledblock.")[0].replace(IDENTIFIER_PREFIX, "");
Done

2020-09-16 21:28 UTC, chriseppstein commented on packages/@css-blocks/ember-app/src/brocolli-plugin.ts
> +          let factoryBlock = await factory.getBlock(block.identifier);
That's great news!

2020-09-16 22:31 UTC, ramitha commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks.ts
> +    if (CSSBlocksService.enableDebugMode) {
I really liked what you suggested about debugging in prod and I was curious to see how to do this. If we have the ember inspector enabled, I can peek into the service instance and its values. So I've made a change to add this on the instance itself.

2020-09-16 23:43 UTC, chriseppstein commented on packages/@css-blocks/ember-app/runtime/app/services/css-blocks.ts
> +    if (CSSBlocksService.enableDebugMode) {
@ramitha oh cool. I'd love to see a demo of that!

2020-09-18 01:52 UTC, merged